import { HoseData } from '@/lib/types/hose';

export const mockedData: HoseData[] = [
  {
    assetId: 1154917,
    hexagonId: 0,
    extSystemCode: 'XX',
    companyCode: 'XX',
    extDocSequenceId: '1234567890',
    requestDate: '2025-02-14T00:00:00.000Z',
    requestTime: '14:30:00',
    documentName: 'ASSETS',
    methodName: 'registerHose',
    customerNumber: '223949',
    otherInfo: 'Some other info',
    customerOrderNumber: 456,
    tessOrderNumber: '123456789',
    tessAsOrderNumber: '30110100',
    organization: 'KUNDER',
    department: 'ALNABRU',
    itemDescription: '5256-06 x 400 mm',
    RFID: 'EE0040589',
    parentSystem: '1203108',
    s1Code: 12,
    s2Code: 0,
    equipmentSubunit: '',
    hoseOtherInfo: 'Some other details',
    customerID: 'EQN-100',
    customerEq: 'customer_eq_01',
    system: 'system_01',
    productionDate: '01-APR-2025',
    installedDate: '01-APR-2025',
    class: 'HTSL',
    status: 'Installed',
    type: 'Kunde utstyr',
    hoseType: '5256-04',
    hoseLength_mm: 400,
    hoseLength_ft_in: '',
    wp_BAR: 200,
    wp_PSI: 2900,
    numberOfHoses: 1,
    ferrule1: '66551-04',
    ferrule2: '66551-04',
    insert1: '31965-04-04',
    insert2: '31965-04-04',
    couplingOrientation: 270,
    pinpricked: true,
    hoseMediumTemperature: 150,
    hoseFunction: '',
    hoseWarranty: '',
    hoseWarrantyComment: '',
    genericHoseType: 'Generic_Type_01',
    typeFittingEnd1: 'Type_01',
    genericDimensionEnd1: 'Dimension_01',
    genderEnd1: 'Male',
    angleEnd1: '45',
    materialQualityEnd1: 'Carbon Steel',
    typeFittingEnd2: 'Type_02',
    genericDimensionEnd2: 'Dimension_02',
    genderEnd2: 'Female',
    angleEnd2: '90',
    generalCommentPTC: 'General comment',
    commentEnd1PTC: 'End 1 comment',
    commentEnd2PTC: 'End 2 comment',
    originalHoseComment: 'Original comment',
    additionalComment: 'Additional comment',
    pressureTest: '1.5',
    testTime: '5 min.',
    testMedium: 'WATER',
    bendingRadius: '90',
    flushingMedia: 'Water',
    primarySystem: '',
    additionalsAend1: '',
    additionalsBend1: '',
    additionalsCend1: '',
    hoseReel: '',
    spiralGuard: '',
    hoseProtection: '',
    additionalsAend2: '',
    additionalsBend2: '',
    additionalsCend2: '',
    hookie: '',
    whipCheck: '',
    breakaway: '',
    inspectedDate: '01-APR-2025',
    inspector: 'Markus Thoresen',
    hoseCondition: 'Hose in good condition',
    approved: true,
    drawingNumber: 'DWG1234',
    posNumber: 'POS5678',
    artNumber: 'ART1234',
    customerArtNumber: 'CART5678',
    criticality: '3 - Medium',
    pollutionExposure: 'E',
    uvExposure: '',
    cleaning: 'FLUSHING',
    flushingStandard: 'Standard',
    customerFlushingMedia: 'Water',
    minimumTemperature: '5°C',
    maximumTemperature: '60°C',
    colorCode: '3',
    spareSetHose: false,
    emergencyHoseLink: '',
    emergencyHoseComment: '',
    currentStatus: 'Open',
  },
  {
    assetId: 27,
    hexagonId: 0,
    extSystemCode: 'XX',
    companyCode: 'XX',
    extDocSequenceId: '1234567890',
    requestDate: '2025-02-14T00:00:00.000Z',
    requestTime: '14:30:00',
    documentName: 'ASSETS',
    methodName: 'registerHose',
    customerNumber: '223949',
    otherInfo: 'Some other info',
    customerOrderNumber: 456,
    tessOrderNumber: '123456789',
    tessAsOrderNumber: '30110100',
    organization: 'KUNDER',
    department: 'ALNABRU',
    itemDescription: '',
    RFID: '',
    parentSystem: '1203108',
    s1Code: 1203108,
    s2Code: null,
    equipmentSubunit: '',
    hoseOtherInfo: 'Some other details',
    customerID: 'EQN-100',
    customerEq: 'customer_eq_01',
    system: 'system_01',
    productionDate: '01-APR-2025',
    installedDate: '01-APR-2025',
    class: 'HTSL',
    status: 'Installed',
    type: 'Kunde utstyr',
    hoseType: '',
    hoseLength_mm: 400,
    hoseLength_ft_in: '',
    wp_BAR: 200,
    wp_PSI: 2900,
    numberOfHoses: 1,
    ferrule1: '',
    ferrule2: '',
    insert1: '31965-04-04',
    insert2: '31965-04-04',
    couplingOrientation: 270,
    pinpricked: true,
    hoseMediumTemperature: 150,
    hoseFunction: '',
    hoseWarranty: '',
    hoseWarrantyComment: '',
    genericHoseType: 'Generic_Type_01',
    typeFittingEnd1: 'Type_01',
    genericDimensionEnd1: 'Dimension_01',
    genderEnd1: 'Male',
    angleEnd1: '45',
    materialQualityEnd1: 'Carbon Steel',
    typeFittingEnd2: 'Type_02',
    genericDimensionEnd2: 'Dimension_02',
    genderEnd2: 'Female',
    angleEnd2: '90',
    generalCommentPTC: 'General comment',
    commentEnd1PTC: 'End 1 comment',
    commentEnd2PTC: 'End 2 comment',
    originalHoseComment: 'Original comment',
    additionalComment: 'Additional comment',
    pressureTest: '1.5',
    testTime: '5 min.',
    testMedium: 'WATER',
    bendingRadius: '90',
    flushingMedia: 'Water',
    primarySystem: '',
    additionalsAend1: '',
    additionalsBend1: '',
    additionalsCend1: '',
    hoseReel: '',
    spiralGuard: '',
    hoseProtection: '',
    additionalsAend2: '',
    additionalsBend2: '',
    additionalsCend2: '',
    hookie: '',
    whipCheck: '',
    breakaway: '',
    inspectedDate: '01-APR-2025',
    inspector: 'Markus Thoresen',
    hoseCondition: 'Hose in good condition',
    approved: true,
    drawingNumber: 'DWG1234',
    posNumber: 'POS5678',
    artNumber: 'ART1234',
    customerArtNumber: 'CART5678',
    criticality: '3 - Medium',
    pollutionExposure: 'E',
    uvExposure: '',
    cleaning: 'FLUSHING',
    flushingStandard: 'Standard',
    customerFlushingMedia: 'Water',
    minimumTemperature: '5°C',
    maximumTemperature: '60°C',
    colorCode: '3',
    spareSetHose: false,
    emergencyHoseLink: '',
    emergencyHoseComment: '',
    currentStatus: 'Open',
  },
  {
    assetId: 30,
    hexagonId: 0,
    extSystemCode: 'XX',
    companyCode: 'XX',
    extDocSequenceId: '1234567890',
    requestDate: '2025-02-14T00:00:00.000Z',
    requestTime: '14:30:00',
    documentName: 'ASSETS',
    methodName: 'registerHose',
    customerNumber: '223949',
    otherInfo: 'Some other info',
    customerOrderNumber: 456,
    tessOrderNumber: '123456789',
    tessAsOrderNumber: '30110100',
    organization: 'KUNDER',
    department: 'ALNABRU',
    itemDescription: '5256-06 x 400 mm',
    RFID: 'EE0040589',
    parentSystem: '1203108',
    s1Code: 1203108,
    s2Code: null,
    equipmentSubunit: '',
    hoseOtherInfo: 'Some other details',
    customerID: 'EQN-100',
    customerEq: 'customer_eq_01',
    system: 'system_01',
    productionDate: '01-APR-2025',
    installedDate: '01-APR-2025',
    class: 'HTSL',
    status: 'Installed',
    type: 'Kunde utstyr',
    hoseType: '5256-04',
    hoseLength_mm: 400,
    hoseLength_ft_in: '',
    wp_BAR: 200,
    wp_PSI: 2900,
    numberOfHoses: 1,
    ferrule1: '66551-04',
    ferrule2: '66551-04',
    insert1: '31965-04-04',
    insert2: '31965-04-04',
    couplingOrientation: 270,
    pinpricked: true,
    hoseMediumTemperature: 150,
    hoseFunction: '',
    hoseWarranty: '',
    hoseWarrantyComment: '',
    genericHoseType: 'Generic_Type_01',
    typeFittingEnd1: 'Type_01',
    genericDimensionEnd1: 'Dimension_01',
    genderEnd1: 'Male',
    angleEnd1: '45',
    materialQualityEnd1: 'Carbon Steel',
    typeFittingEnd2: 'Type_02',
    genericDimensionEnd2: 'Dimension_02',
    genderEnd2: 'Female',
    angleEnd2: '90',
    generalCommentPTC: 'General comment',
    commentEnd1PTC: 'End 1 comment',
    commentEnd2PTC: 'End 2 comment',
    originalHoseComment: 'Original comment',
    additionalComment: 'Additional comment',
    pressureTest: '1.5',
    testTime: '5 min.',
    testMedium: 'WATER',
    bendingRadius: '90',
    flushingMedia: 'Water',
    primarySystem: '',
    additionalsAend1: '',
    additionalsBend1: '',
    additionalsCend1: '',
    hoseReel: '',
    spiralGuard: '',
    hoseProtection: '',
    additionalsAend2: '',
    additionalsBend2: '',
    additionalsCend2: '',
    hookie: '',
    whipCheck: '',
    breakaway: '',
    inspectedDate: '01-APR-2025',
    inspector: 'Markus Thoresen',
    hoseCondition: 'Hose in good condition',
    approved: true,
    drawingNumber: 'DWG1234',
    posNumber: 'POS5678',
    artNumber: 'ART1234',
    customerArtNumber: 'CART5678',
    criticality: '3 - Medium',
    pollutionExposure: 'E',
    uvExposure: '',
    cleaning: 'FLUSHING',
    flushingStandard: 'Standard',
    customerFlushingMedia: 'Water',
    minimumTemperature: '5°C',
    maximumTemperature: '60°C',
    colorCode: '3',
    spareSetHose: false,
    emergencyHoseLink: '',
    emergencyHoseComment: '',
    currentStatus: 'Open',
  },
  {
    assetId: 31,
    hexagonId: 0,
    extSystemCode: 'XX',
    companyCode: 'XX',
    extDocSequenceId: '1234567890',
    requestDate: '2025-02-14T00:00:00.000Z',
    requestTime: '14:30:00',
    documentName: 'ASSETS',
    methodName: 'registerHose',
    customerNumber: '223949',
    otherInfo: 'Some other info',
    customerOrderNumber: 456,
    tessOrderNumber: '123456789',
    tessAsOrderNumber: '30110100',
    organization: 'KUNDER',
    department: 'ALNABRU',
    itemDescription: '5256-06 x 400 mm',
    RFID: 'EE0040589',
    parentSystem: '1203108',
    s1Code: 1203108,
    s2Code: null,
    equipmentSubunit: '',
    hoseOtherInfo: 'Some other details',
    customerID: 'EQN-100',
    customerEq: 'customer_eq_01',
    system: 'system_01',
    productionDate: '01-APR-2025',
    installedDate: '01-APR-2025',
    class: 'HTSL',
    status: 'Installed',
    type: 'Kunde utstyr',
    hoseType: '5256-04',
    hoseLength_mm: 400,
    hoseLength_ft_in: '',
    wp_BAR: 200,
    wp_PSI: 2900,
    numberOfHoses: 1,
    ferrule1: '66551-04',
    ferrule2: '66551-04',
    insert1: '31965-04-04',
    insert2: '31965-04-04',
    couplingOrientation: 270,
    pinpricked: true,
    hoseMediumTemperature: 150,
    hoseFunction: '',
    hoseWarranty: '',
    hoseWarrantyComment: '',
    genericHoseType: 'Generic_Type_01',
    typeFittingEnd1: 'Type_01',
    genericDimensionEnd1: 'Dimension_01',
    genderEnd1: 'Male',
    angleEnd1: '45',
    materialQualityEnd1: 'Carbon Steel',
    typeFittingEnd2: 'Type_02',
    genericDimensionEnd2: 'Dimension_02',
    genderEnd2: 'Female',
    angleEnd2: '90',
    generalCommentPTC: 'General comment',
    commentEnd1PTC: 'End 1 comment',
    commentEnd2PTC: 'End 2 comment',
    originalHoseComment: 'Original comment',
    additionalComment: 'Additional comment',
    pressureTest: '1.5',
    testTime: '5 min.',
    testMedium: 'WATER',
    bendingRadius: '90',
    flushingMedia: 'Water',
    primarySystem: '',
    additionalsAend1: '',
    additionalsBend1: '',
    additionalsCend1: '',
    hoseReel: '',
    spiralGuard: '',
    hoseProtection: '',
    additionalsAend2: '',
    additionalsBend2: '',
    additionalsCend2: '',
    hookie: '',
    whipCheck: '',
    breakaway: '',
    inspectedDate: '01-APR-2025',
    inspector: 'Markus Thoresen',
    hoseCondition: 'Hose in good condition',
    approved: true,
    drawingNumber: 'DWG1234',
    posNumber: 'POS5678',
    artNumber: 'ART1234',
    customerArtNumber: 'CART5678',
    criticality: '3 - Medium',
    pollutionExposure: 'E',
    uvExposure: '',
    cleaning: 'FLUSHING',
    flushingStandard: 'Standard',
    customerFlushingMedia: 'Water',
    minimumTemperature: '5°C',
    maximumTemperature: '60°C',
    colorCode: '3',
    spareSetHose: false,
    emergencyHoseLink: '',
    emergencyHoseComment: '',
    currentStatus: 'Open',
  },
];

export const mockedHistory = [
  {
    id: '4140106',
    date: new Date(2024, 11, 31, 10, 30),
    name: '2239FULL',
    comments:
      'Updated customer database with new contact information and verified all entries.',
  },
  {
    id: '4140107',
    date: new Date(2024, 10, 15, 14, 0),
    name: '1105PART',
    comments: 'Performed routine maintenance check. System operating normally.',
  },
  {
    id: '4140108',
    date: new Date(2023, 0, 20, 9, 15),
    name: 'SUSER',
    comments:
      'Initial setup and configuration of the hose asset in the system.',
  },
];
