import { HoseData } from '@/lib/types/hose';

export const mockedData: Partial<HoseData>[] = [
  {
    id: '1',
    description: 'Hydraulic hose for heavy machinery',
    prodDate: '2022-01-01T00:00:00.000Z',
    customerId: 'CUST-1234',
    hoseType: 'Hydraulic',
    s1PlantVesselUnit: 'S1-123',
    S2Equipment: 'S2-456',
    equipmentSubunit: 'E1-789',
    otherInfo: 'High-pressure hose',
    RFid: 'RFID-1234',
    hoseMediumTemperature: '150°C',
    hoseFunction: 'Hydraulic fluid transfer',
    pollutionExposure: 'Low',
    uvExposure: 'Medium',
    installationDate: '2022-02-01T00:00:00.000Z',
    hoseStandard: 'SAE 100R1',
    innerDiameter: '1.5 inches',
    totalLength: '20 feet',
    wpBar: '250 bar',
    wpPsi: '3625 psi',
    materialQuality: 'High-quality rubber',
    typeFitting: 'JIC 37° flare',
    innerDiameter2: '1.25 inches',
    gender: 'Male',
    angle: '90°',
    commentEnd1: 'End 1 comment',
    materialQuality2: 'High-quality rubber',
    typeFitting2: 'JIC 37° flare',
    gender2: 'Female',
    angle2: '90°',
    commentEnd2: 'End 2 comment',
  },
  {
    id: '2',
    description: 'Industrial hose for chemical transfer',
    prodDate: '2022-02-01T00:00:00.000Z',
    customerId: 'CUST-5678',
    hoseType: 'Industrial',
    s1PlantVesselUnit: 'S1-901',
    S2Equipment: 'S2-234',
    equipmentSubunit: 'E1-567',
    otherInfo: 'Chemical-resistant hose',
    RFid: 'RFID-5678',
    hoseMediumTemperature: '100°C',
    hoseFunction: 'Chemical transfer',
    pollutionExposure: 'Medium',
    uvExposure: 'High',
    installationDate: '2022-03-01T00:00:00.000Z',
    hoseStandard: 'ANSI/ASME B31.3',
    innerDiameter: '2 inches',
    totalLength: '30 feet',
    wpBar: '150 bar',
    wpPsi: '2175 psi',
    materialQuality: 'High-quality PTFE',
    typeFitting: 'NPT',
    innerDiameter2: '1.75 inches',
    gender: 'Male',
    angle: '45°',
    commentEnd1: 'End 1 comment',
    materialQuality2: 'High-quality PTFE',
    typeFitting2: 'NPT',
    gender2: 'Female',
    angle2: '45°',
    commentEnd2: 'End 2 comment',
  },
];
