import { Hose } from '@/lib/types/hose';

const hoses: Hose<number | string>[] = [
  {
    hoseHeader: {
      hoseLineId: 2540,
      assetId: 2540,
      extSystemCode: 'HM',
      companyCode: '01',
      extDocSequenceId: 'RH00000001Z8',
      requestDate: '2025-08-29T00:00:00.000Z',
      requestTime: '10:26:33',
      documentName: 'ASSETS',
      methodName: 'registerHose',
      customerNumber: '223949',
      otherInfo: 'Deck Crane',
      customerOrderNumber: 'test1',
      tessOrderNumber: 'NaN',
      tessAsOrderNumber: '',
      organization: 'KUNDER',
      department: 'SUBSEA',
    },
    hoseLine: {
      hoseLineId: 2540,
      assetId: 2540,
      hexagonId: '1137200',
      itemDescription: '2SN-10 x 1550 mm TETA',
      rfid: '',
      state: 'GOOD',
      classOrg: '*',
      parentSystemId: 83,
      s1: {
        s1Id: 76,
        s1Code: '1203108',
        s1Name: 'TEST',
        customerId: 313693,
      },
      s2: {
        s2Id: 220,
        s2Code: '1203109',
        s2Name: 'Deck Crane (Training Hoses)',
        s1Id: 76,
      },
      equipmentSubunit: '',
      customerId: 313693,
      customerEq: '1572-03',
      system: 'STB',
      productionDate: '29-AUG-2025',
      installedDate: '',
      numberOfHoses: '1',
      genericHoseType: {
        genericHoseTypeId: 73,
        genericHoseTypeName: '2SN -10',
      },
      generalCommentPtc: 'This is a test',
      originalHoseComment: '',
      additionalComment: '',
      primarySystem: '',
      hoseReel: '',
      spiralGuard: '91333-18-1',
      hoseProtection: '92340-1',
      hookie: '',
      whipcheck: '',
      breakaway: '',
      currentStatus: 'Processed',
    },
    hoseData: {
      hoseLineId: 2540,
      assetId: 2540,
      class: {
        classId: 2,
        className: 'HTSL',
      },
      status: {
        statusId: 1,
        status: 'Delivered',
      },
      type: {
        typeId: 156,
        typeName: '529-10',
      },
      hoseTypeId: {
        hoseTypeId: 155,
        hoseTypeName: '529-10',
      },
      hoselengthMm: 1550,
      hoselengthFtIn: '',
      wpBar: 250,
      wpPsi: 3625,
      ferrule1: '65124-10',
      ferrule2: '65124-10',
      insert1: '***',
      insert2: '***',
      hoseDimension: {
        hoseDimensionId: 1,
        hoseDimension: '',
      },
      hoseOtherInfo: '',
      couplingOrientationId: {
        couplingOrientationId: 3,
        orientationCode: '0°',
      },
      pinPricked: false,
      hoseMediumTemperature: 'OIL',
      hoseFunction: 'Hydraulic hose',
      hoseWarranty: 'NO',
      hoseWarrantyComment: '',
    },
    customerData: {
      hoseLineId: 2540,
      assetId: 2540,
      drawingNumber: '1408-33-166',
      posNumber: '',
      artNumber: '9987633-05',
      customerArtNumber: '2222-10',
      criticality: {
        criticalityId: 8,
        criticalityName: '2 - Low',
      },
      pollutionExposure: 'E',
      uxExposure: '',
      cleaning: '',
      flushingStandard: '',
      flushingMedia: {
        flushingMediaId: 1,
        flushingMediaName: '',
      },
      minimumTemperature: '',
      maximumTemperature: '',
      colorId: 1,
      spareSetHose: false,
      emergencyHoseLink: '',
      emergencyHoseComment: '1143344',
      partNumberUpdatesNeeded: false,
    },
    testing: {
      hoseLineId: 2540,
      assetId: 2540,
      testTime: '5 min.',
      testMediumStats: '',
      pressureTestStatus: '',
      bendingRadius: '',
      thirdPartySharing: '',
    },
    maintenanceDetails: {
      hoseLineId: 2540,
      assetId: 2540,
      inspectedDate: '',
      inspector: '',
      hoseCondition: '',
      approved: false,
      inspectionComment: '',
      nextInspectionDate: '29-AUG-2028',
      pressureTestDate: '9-FEB-2016',
      pressureTestOnInterval: false,
      nextPressureTest: '9-FEB-2019',
      nextHoseReplacement: '29-AUG-2035',
    },
    hoseFitting1: {
      hoseLineId: 2540,
      assetId: 2540,
      fittingType: 1,
      typeFittingEnd: {
        typeFittingEndId: '',
        fittingEnd: '',
        genericDimensionEndId: 37,
      },
      genericDimensionEnd: {
        genericDimensionEndId: 37,
        genericDimensionName: '20S M30x2',
      },
      genderEnd: 'Female',
      angleEnd: '90°',
      materialQualityEnd: 'AISI 316',
      commentEndPtc: 'Densotape ende 1',
    },
    hoseFitting2: {
      hoseLineId: 2540,
      assetId: 2540,
      fittingType: 2,
      typeFittingEnd: {
        typeFittingEndId: '',
        fittingEnd: '',
        genericDimensionEndId: '',
      },
      genericDimensionEnd: {
        genericDimensionEndId: '',
        genericDimensionName: '20S M30x2',
      },
      genderEnd: 'Male',
      angleEnd: '0°',
      materialQualityEnd: 'AISI 316',
      commentEndPtc: 'Densotape ende 2',
    },
    additionals: {
      hoseLineId: 2540,
      assetId: 2540,
      aEnd1: '***',
      bEnd1: '***',
      cEnd1: '***',
      dEnd1: '',
      eEnd1: '',
      fEnd1: '',
      gEnd1: '',
      hEnd1: '',
      aEnd2: '***',
      bEnd2: '***',
      cEnd2: '***',
      dEnd2: '',
      eEnd2: '',
      fEnd2: '',
      gEnd2: '',
      hEnd2: '',
    },
  },
];
